AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  GO_fun
  
  Sample SAM Template for GO_fun

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  UserS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  GetUsersFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: getUsers/
      Handler: getUsers
      Runtime: go1.x
      Policies: AmazonDynamoDBFullAccess
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        GetUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          TABLE: "Users"

  CreateUsersFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: createUsers/
      Handler: createUsers
      Runtime: go1.x
      Policies: AmazonDynamoDBFullAccess
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        PostUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          TABLE: "Users" 

  # GatewayApi:
  #   Type: AWS::Serverless::Api
  #   DependsOn:
  #     - GetUsersFunction
  #     - CreateUsersFunction
  #   Properties: 
  #     StageName: Prod
  #     Models:
  #       User:
  #         type: object
  #         required: # Can leave this section out if there are no required Properties in the list below
  #           - DeviceId
  #           - FirstName
  #           - LastName
  #         properties:
  #           UserId:
  #             type: string
  #           DeviceId:
  #             type: string
  #           FirstName:
  #             type: string
  #           LastName:
  #             type: string

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UsersAPI:
    Description: "API Gateway endpoint URL for Prod environment for Users Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/"
  GetUsersFunction:
    Description: "GetUsers Lambda Function ARN"
    Value: !GetAtt GetUsersFunction.Arn
  CreateUsersFunction:
    Description: "CreateUsers Lambda Function ARN"
    Value: !GetAtt CreateUsersFunction.Arn
