name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v1
      - name: Run sam build --parameter-overrides NRAccountId=${{ secrets.NEW_RELIC_ACCOUNT_ID }}
        run: sam build
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Run Tests
        run: go test -v ./...
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name users-functions --s3-bucket githubbuild --capabilities CAPABILITY_NAMED_IAM --region us-east-1

  # You can run these steps all in one job like above which is faster, or seperate them into multiple jobs like below
  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.16.x
  #     - uses: actions/checkout@v2
  #     - name: Run Tests
  #       run: go test -v ./...
      
  # deploy:
  #   needs: [build, test]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: aws-actions/setup-sam@v1
  #     - uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-west-1
  #     - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name prod-users-func --s3-bucket serverlessplayground --capabilities CAPABILITY_IAM --region us-west-1 
